ARG CUDA_VERSION
ARG ROCKY_VERSION
FROM nvidia/cuda:${CUDA_VERSION}-devel-rockylinux${ROCKY_VERSION}
LABEL maintainer="AliceVision Team alicevision-team@googlegroups.com"

# Accept AV_DEPS_VERSION for selective dependency rebuilding
ARG AV_DEPS_VERSION=2025.02.21
ENV AV_DEPS_VERSION=${AV_DEPS_VERSION}

# use CUDA_VERSION to select the image version to use
# see https://hub.docker.com/r/nvidia/cuda/
#
# AV_VERSION=2.2.8.develop
# CUDA_VERSION=11.0
# ROCKY_VERSION=20.04
# docker build \
#    --build-arg CUDA_VERSION=${CUDA_VERSION} \
#    --build-arg ROCKY_VERSION${ROCKY_VERSION} \
#    --build-arg AV_DEPS_VERSION=${AV_DEPS_VERSION} \
#    --tag alicevision/alicevision-deps:${AV_VERSION}-rocky${ROCKY_VERSION}-cuda${CUDA_TAG} \
#     -f Dockerfile_rocky_deps .

# OS/Version (FILE): cat /etc/issue.net
# Cuda version (ENV): $CUDA_VERSION

RUN dnf install -y 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled devel
RUN dnf install -y epel-release
# RUN dnf install -y gcc-toolset-13-gcc-c++
# RUN dnf remove -y gcc-g++ gcc
# RUN update-alternatives --install /usr/bin/gcc gcc /opt/rh/gcc-toolset-13/root/usr/bin/gcc 60
# RUN update-alternatives --install /usr/bin/g++ g++ /opt/rh/gcc-toolset-13/root/usr/bin/g++ 60
# RUN update-alternatives --install /usr/bin/cpp cpp /opt/rh/gcc-toolset-13/root/usr/bin/cpp 60
RUN dnf install -y ca-certificates wget
RUN dnf install -y cmake git unzip
RUN dnf install -y python3-devel python3-pip
RUN dnf install -y pcre2-devel
RUN dnf install -y xerces-c-devel
RUN dnf install -y bison
RUN dnf install -y diffutils which file
RUN dnf install -y yasm
RUN dnf install -y gfortran libasan libubsan
RUN dnf update -y
# RUN scl enable gcc-toolset-13 bash

RUN python3 -m pip install numpy

ENV AV_DEV=/opt/AliceVision_git \
    AV_BUILD=/tmp/AliceVision_build \
    AV_INSTALL=/opt/AliceVision_install \
    PATH="${PATH}:${AV_BUNDLE}"

# Create directories needed for the build process
RUN mkdir -p ${AV_DEV} ${AV_BUILD} ${AV_BUILD}/external ${AV_INSTALL}/share/aliceVision

COPY dl/vlfeat_K80L3.SIFT.tree ${AV_INSTALL}/share/aliceVision/
RUN echo "export ALICEVISION_VOCTREE=${AV_INSTALL}/share/aliceVision/vlfeat_K80L3.SIFT.tree" >> /etc/profile.d/alicevision.sh

COPY dl/sphereDetection_Mask-RCNN.onnx ${AV_INSTALL}/share/aliceVision/
RUN echo "export ALICEVISION_SPHERE_DETECTION_MODEL=${AV_INSTALL}/share/aliceVision/sphereDetection_Mask-RCNN.onnx" >> /etc/profile.d/alicevision.sh

COPY dl/fcn_resnet50.onnx ${AV_INSTALL}/share/aliceVision/
RUN echo "export ALICEVISION_SEMANTIC_SEGMENTATION_MODEL=${AV_INSTALL}/share/aliceVision/fcn_resnet50.onnx" >> /etc/profile.d/alicevision.sh

COPY dl/ColorchartDetectionModel ${AV_INSTALL}/share/aliceVision
RUN echo "export ALICEVISION_COLORCHARTDETECTION_MODEL_FOLDER=${AV_INSTALL}/share/aliceVision/ColorchartDetectionModel" >> /etc/profile.d/alicevision.sh

COPY docker/check-cpu.sh ${AV_DEV}/docker/check-cpu.sh
RUN export CPU_CORES=`${AV_DEV}/docker/check-cpu.sh` && echo "Build multithreading number of cores: ${CPU_CORES}"

COPY CMakeLists.txt ${AV_DEV}/
COPY src ${AV_DEV}/src

COPY dl/deps ${AV_BUILD}/external/download/

WORKDIR "${AV_BUILD}"
RUN cmake "${AV_DEV}" \
     -DCMAKE_BUILD_TYPE=Release \
     -DALICEVISION_BUILD_DEPENDENCIES:BOOL=ON \
     -DAV_BUILD_ZLIB:BOOL=ON \
     -DAV_BUILD_ALICEVISION:BOOL=OFF \
     -DAV_DEPS_VERSION=${AV_DEPS_VERSION} \
     -DCMAKE_INSTALL_PREFIX="${AV_INSTALL}"

# Symlink lib64 to lib as qtOIIO expects to find OIIO in lib64
RUN mkdir -p "${AV_INSTALL}/lib" && \
    ln -s lib "${AV_INSTALL}/lib64"

RUN test -e /usr/local/cuda/lib64/libcublas.so || ln -s /usr/lib/x86_64-linux-gnu/libcublas.so /usr/local/cuda/lib64/libcublas.so

# Build the dependencies - using cmake --build which will build targets selectively
RUN cmake --build . -j $(${AV_DEV}/docker/check-cpu.sh) && \
   mv "${AV_INSTALL}/bin" "${AV_INSTALL}/bin-deps" && \
   rm -rf "${AV_BUILD}"